steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--target', '${_DOCKER_STAGE_NAME}', '-t', '${_IMAGE}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run','deploy', '${_PROJECT_NAME}',
      '--project', '${_PROJECT_ID}',
      '--image', '${_IMAGE}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - ${_IMAGE}
